export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'

export const FIND_POST_REQUEST = 'FIND_POST_REQUEST'
export const FIND_POST_SUCCESS = 'FIND_POST_SUCCESS'
export const FIND_POST_ERROR = 'FIND_POST_ERROR'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'

export const DESTROY_POST_REQUEST = 'DESTROY_POST_REQUEST'
export const DESTROY_POST_SUCCESS = 'DESTROY_POST_SUCCESS'
export const DESTROY_POST_ERROR = 'DESTROY_POST_ERROR'